server:
    port: 8090

spring:
  application:
    name: user-manager

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:user_manager;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

github:
  public-url: https://github.com
  api:
    url: https://api.github.com
    api-key: